import { Icon } from "../components/ui/icons";

const PIPELINE_STEPS = [
  "Weather Data",
  "Validation",
  "Preprocessing",
  "Feature Engineering",
  "Model",
  "Prediction",
  "Explanation",
];

export default function About() {
  return (
    <div className="page-content">
      <div className="page-header">
        <h1>About Flood Prediction System ZM</h1>
      </div>

      <div className="grid grid-auto" style={{ marginBottom: "1.25rem" }}>
        <div className="card">
          <div className="icon-chip">
            <Icon name="ml" />
          </div>
          <h3 style={{ margin: "0 0 0.3rem" }}>AI &amp; Machine Learning</h3>
          <p className="text-secondary" style={{ margin: 0 }}>
            Baseline and time-series models compared honestly on held-out data.
          </p>
        </div>
        <div className="card">
          <div className="icon-chip">
            <Icon name="data" />
          </div>
          <h3 style={{ margin: "0 0 0.3rem" }}>Real-time Data</h3>
          <p className="text-secondary" style={{ margin: 0 }}>
            Meteorological observations from documented, cited sources.
          </p>
        </div>
        <div className="card">
          <div className="icon-chip">
            <Icon name="geo" />
          </div>
          <h3 style={{ margin: "0 0 0.3rem" }}>Geospatial Analysis</h3>
          <p className="text-secondary" style={{ margin: 0 }}>
            Location-based monitoring across Zambian provinces and districts.
          </p>
        </div>
        <div className="card">
          <div className="icon-chip">
            <Icon name="warning" />
          </div>
          <h3 style={{ margin: "0 0 0.3rem" }}>Early Warnings</h3>
          <p className="text-secondary" style={{ margin: 0 }}>
            Dashboard-first alerting, independent of any external delivery provider.
          </p>
        </div>
      </div>

      <div className="card" style={{ maxWidth: 900 }}>
        <p className="text-secondary">
          Flood Prediction System ZM is an AI-powered flood prediction and early-warning
          research system for the Zambian context. It uses historical and near-real-time
          meteorological data, machine learning, and explainable AI to estimate flood
          risk and provide actionable early warnings for citizens, communities, farmers,
          disaster-management personnel, local authorities, and emergency-response
          organizations.
        </p>
        <p className="text-secondary">
          <strong>
            Flood Prediction System ZM's predictions are risk estimates generated from available data and
            should support, not replace, professional emergency-management decisions.
          </strong>
        </p>

        <h3>Methodology pipeline</h3>
        <div className="pipeline-steps">
          {PIPELINE_STEPS.map((step, i) => (
            <span key={step} style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
              <span className="pipeline-step">{step}</span>
              {i < PIPELINE_STEPS.length - 1 && <span className="pipeline-arrow">→</span>}
            </span>
          ))}
        </div>
        <p className="text-muted" style={{ marginTop: 0 }}>
          See <code>docs/ML-METHODOLOGY.md</code> for the full methodology, including open
          data-labeling questions this pipeline has not yet resolved.
        </p>

        <h3>Current limitations</h3>
        <ul className="text-secondary">
          <li>
            <strong>The model does not demonstrate predictive skill.</strong> Across 25
            configurations, 15 rolling-origin folds and 10 spatio-temporal folds, no model
            beat a day-of-year seasonal baseline that uses no weather data at all. The
            formal deployment gate returned <code>DO_NOT_DEPLOY</code>. This is a research
            result, not an operational warning system.
          </li>
          <li>
            <strong>Flood labels are incomplete</strong>, and this is the binding
            constraint. Several years contain no documented district-level Zambian events
            at all, so those periods' non-flood days are unverified.
          </li>
          <li>
            <strong>There is no forecast capability.</strong> The system scores a 7-day
            horizon using NASA POWER weather that lags 2–3 days, so the horizon is not yet
            operationally real.
          </li>
          <li>
            <strong>Precision is unusable for alerting</strong> — roughly one false alarm
            per district every two days at the documented operating point.
          </li>
          <li>
            Spatial resolution (~55 km reanalysis cells) cannot resolve urban flooding at
            settlement scale, and predictions are generated by a manual run, not a
            scheduler.
          </li>
          <li>Alert delivery to external channels (SMS/email) is not configured — alerts are dashboard-only.</li>
        </ul>
        <p className="text-muted">See docs/LIMITATIONS.md in the project repository for the full list.</p>
      </div>
    </div>
  );
}
